model:
  deepseek: "deepseek-r1-distill-llama-70b"
  gemma: "gemma2-9b-it"
  llama: "llama-3.1-8b-instant"
  temperature: 0.0

prompt:

  system_template_it: >
   Sei un esperto linguista italiano. 

  system_template_en: >
    You are an expert Italian linguist. 

  user_template_it: >
    Traduci da italiano antico a italiano moderno, tenendo conto dei modi di dire e scrivere dei tempi medievali e rinascimentali,
    scrivimi solo la traduzione senza aggiungere altro.

    {examples}


    Antico: '{old_sentence}'
    Moderno:

  user_template_en: >
    Translate from Old Italian to Modern Italian, taking into account the ways of speaking and writing of the medieval and Renaissance periods,
    just write me the translation without adding anything else.

    {examples}

    
    Archaic: '{old_sentence}'
    Modern: 

  system_template_judge_tournament_en: >
    You are an expert Italian linguist evaluator, tasked with evaluating two translations (A, B) of a source text.
    
  user_template_judge_tournament_en: >
   Your goal is to decide which translation is better based on the gold translation

    Old sentence: {old_sentence}
    A: {A}
    B: {B}
    Gold translation: {gold}

    Please read the 'Old sentence' and 'gold sentence' and both translations 'A' and 'B', then write only your choice A or B, no other comments.

  system_template_judge: >
     You are an expert Italian linguist and translation evaluator. Your task is to assess a translation of a sentence from old italian into modern Italian. You must assign a score from 1 to 5 for each of the following evaluation criteria. Provide only the requested scores, without explanations or additional commentary.

  user_template_judge: >
   Evaluate the translation using these five criteria:
   
   Meaning Preservation
    1: Completely diverges in meaning, major misinterpretations or hallucinations
    2: Core ideas are misrepresented or lost, with significant meaning shift
    3: Mostly correct meaning, but with noticeable errors (minor shifts or omissions)
    4: Meaning is preserved with minor discrepancies or nuances lost
    5: Fully faithful to the original meaning

   Grammar
    1: Barely readable or nonsensical
    2: Grammatically flawed throughout, affecting understanding
    3: Minor grammatical or syntactic errors, but understandable
    4: Fluent, with native-like grammar and syntax, but minor oddities
    5: Perfectly fluent and natural in the target Language

    Modern Structural Effectiveness
    1: Structure is archaic or rigid, hard to follow; mimics original in a way that hinders readability.
    2: Structure is awkward or overly literal; noticeably unnatural for modern Italian.
    3: Mixed structure; understandable but includes dated or clumsy phrasing.
    4: Mostly fluent and modern structure; minor awkwardness or stiffness remains.
    5: Fully natural and idiomatic structure; clear, fluent, and appropriate for contemporary Italian.

    Completeness
    1: Large parts missing or major hallucinated content
    2: Multiple omissions or additions altering meaning
    3: Minor omissions or additions that don’t significantly alter meaning
    4: Nearly complete with only slight trimming
    5: Fully complete with no omissions or additions

    Lexical Modernization
    1: No modernization; reads like the original.
    2: Mostly archaic or unnatural word choices.
    3: Mixture of modern and archaic.
    4: Slightly dated or formal, but still acceptable in modern Italian.
    5: Modern terms feel natural, idiomatic, and true to current Italian usage.
    
    Provide your evaluation in the following format (use only this format, without extra text):

    Meaning Preservation: <score>, Grammar: <score>, Style Matching: <score>, Structural Alignment: <score>, Completeness: <score>

    Original sentence: {old_sentence}
    Translation: {translation}

prometheus_judge:
  relative:
   system_prompt: "You are a fair judge assistant tasked with providing clear, objective feedback based on specific criteria, ensuring each assessment reflects the absolute standards set for performance."
   user_prompt: > 
    ###Task Description:
    An instruction, two responses (A and B), and a score rubric are given.

    1. Compare Response A and Response B based on the given rubric.
    2. Determine which one is better and explain **why**, using objective criteria from the rubric.
    3. After the explanation, return your judgment in the following format:

    "[Result]: Response (A/B) is better."

    4. Do not generate any other opening, closing, or unrelated text.

    ###The instruction to evaluate:
    You need to choose the better translation from old Italian sentence into modern Italian between two translations.

    ###Response A:
    {response_a}

    ###Response B:
    {response_b}

    ###Reference Answer (Gold):
    {reference_answer}

    ###Score Rubric:
    Is the translation faithful to the original meaning, grammatically correct, structurally modern, complete, and lexically modernized?

    ###Feedback:
  absolute:
    system_prompt: "You are a fair judge assistant tasked with providing clear, objective feedback based on specific criteria, ensuring each assessment reflects the absolute standards set for performance."
    user_prompt: > 
      ###Task Description:
      An instruction, a response to evaluate, a reference answer that gets a score of 5, and a score rubric representing a evaluation criteria are given.
      1. Write a detailed feedback that assess the quality of the response strictly based on the given score rubric, not evaluating in general.
      2. After writing a feedback, write a score that is an integer between 1 and 5. You should refer to the score rubric.
      3. The output format should look as follows: "Feedback: (write a feedback for criteria) [RESULT] (an integer number between 1 and 5)"
      4. Please do not generate any other opening, closing, and explanations.

      ###The instruction to evaluate:
      You need to evaluate the translation of an old Italian sentence into modern Italian based on the reference answer that gets a score of 5.

      ###Response to evaluate:
      {response}

      ###Reference Answer (Score 5):
      {reference_answer}

      ###Score Rubrics:
      {rubric}

      ###Feedback: 
        
data:
  input_file: "data/dataset_cleaned.csv"

rate_limit:
  req_per_min: 30

