model:
  deepseek: "deepseek-r1-distill-llama-70b"
  gemma: "gemma2-9b-it"
  llama: "llama-3.1-8b-instant"
  temperature: 0.0

prompt:

  system_template_it: >
   Sei un esperto linguista italiano. 

  system_template_en: >
    You are an expert Italian linguist. 

  user_template_it: >
    Traduci da italiano antico a italiano moderno, tenendo conto dei modi di dire e scrivere dei tempi medievali e rinascimentali,
    scrivimi solo la traduzione senza aggiungere altro.

    {examples}


    Antico: '{old_sentence}'
    Moderno:

  user_template_en: >
    Translate from Old Italian to Modern Italian, taking into account the ways of speaking and writing of the medieval and Renaissance periods,
    just write me the translation without adding anything else.

    {examples}

    
    Archaic: '{old_sentence}'
    Modern: 

  system_template_judge_tournament_en: >
    You are an expert Italian linguist evaluator, tasked with evaluating two translations (A, B) of a source text.
    
  user_template_judge_tournament_en: >
   Your goal is to decide which translation is better based on the following criteria:
    -Meaning Preservation: the best is a fully faithful to the original meaning translation
    -Grammar: the best is a grammar perfectly fluent and natural in the target Language
    -Style Matching: the best is that style and register match the source perfectly
    -Structural Alignment: the best is that mirrors sentence and paragraph structure effectively

    Old sentence: {old_sentence}
    Translation A: {A}
    Translation B: {B}

    Please read the old sentence text and both translations, then write only the choice A or B.


  
data:
  input_file: "data/dataset_cleaned.csv"

rate_limit:
  req_per_min: 30

