model:
  deepseek: "deepseek-r1-distill-llama-70b"
  gemma: "gemma2-9b-it"
  llama: "llama-3.1-8b-instant"
  temperature: 0.0

prompt:
  system_template_it: >
   Sei un esperto linguista italiano. Traduci da italiano antico a italiano moderno.

  system_template_en: >
    You are an expert Italian linguist. Translate from Old Italian to Modern Italian.

  user_template_it: >
    {examples}


    Traduci '{old_sentence}' tenendo conto dei modi di dire e scrivere dei tempi medievali e rinascimentali,
    scrivimi solo la traduzione senza aggiungere altro.

  template_en: >
    {examples}

    
    Translate '{old_sentence}' taking into account the ways of speaking and writing of the medieval and Renaissance periods,
    just write me the translation without adding anything else.

rate_limit:
  req_per_min: 30

